//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap add32 {
        get {
            object obj = ResourceManager.GetObject("add32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap cls32 {
        get {
            object obj = ResourceManager.GetObject("cls32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap del32 {
        get {
            object obj = ResourceManager.GetObject("del32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap del32_white {
        get {
            object obj = ResourceManager.GetObject("del32-white", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap del64 {
        get {
            object obj = ResourceManager.GetObject("del64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap drive16 {
        get {
            object obj = ResourceManager.GetObject("drive16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap edit32 {
        get {
            object obj = ResourceManager.GetObject("edit32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap facebook32 {
        get {
            object obj = ResourceManager.GetObject("facebook32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap file16 {
        get {
            object obj = ResourceManager.GetObject("file16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap find128 {
        get {
            object obj = ResourceManager.GetObject("find128", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap find32 {
        get {
            object obj = ResourceManager.GetObject("find32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap find64 {
        get {
            object obj = ResourceManager.GetObject("find64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap folder16 {
        get {
            object obj = ResourceManager.GetObject("folder16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap g_32 {
        get {
            object obj = ResourceManager.GetObject("g+32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap help32 {
        get {
            object obj = ResourceManager.GetObject("help32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap home32 {
        get {
            object obj = ResourceManager.GetObject("home32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap info32 {
        get {
            object obj = ResourceManager.GetObject("info32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap invert32 {
        get {
            object obj = ResourceManager.GetObject("invert32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap invert64 {
        get {
            object obj = ResourceManager.GetObject("invert64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap lang32 {
        get {
            object obj = ResourceManager.GetObject("lang32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap license32 {
        get {
            object obj = ResourceManager.GetObject("license32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap load32 {
        get {
            object obj = ResourceManager.GetObject("load32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap load32_white {
        get {
            object obj = ResourceManager.GetObject("load32-white", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap load64 {
        get {
            object obj = ResourceManager.GetObject("load64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap location32 {
        get {
            object obj = ResourceManager.GetObject("location32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap location64 {
        get {
            object obj = ResourceManager.GetObject("location64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap logo128 {
        get {
            object obj = ResourceManager.GetObject("logo128", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap logo64 {
        get {
            object obj = ResourceManager.GetObject("logo64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap more32 {
        get {
            object obj = ResourceManager.GetObject("more32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap move32_3 {
        get {
            object obj = ResourceManager.GetObject("move32_3", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap move64 {
        get {
            object obj = ResourceManager.GetObject("move64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap network16 {
        get {
            object obj = ResourceManager.GetObject("network16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap opt32 {
        get {
            object obj = ResourceManager.GetObject("opt32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap path32_2 {
        get {
            object obj = ResourceManager.GetObject("path32_2", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap path64 {
        get {
            object obj = ResourceManager.GetObject("path64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap properties32 {
        get {
            object obj = ResourceManager.GetObject("properties32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap properties64 {
        get {
            object obj = ResourceManager.GetObject("properties64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap recycle32 {
        get {
            object obj = ResourceManager.GetObject("recycle32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap recycle64 {
        get {
            object obj = ResourceManager.GetObject("recycle64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap reset32 {
        get {
            object obj = ResourceManager.GetObject("reset32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap rom16 {
        get {
            object obj = ResourceManager.GetObject("rom16", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap run32 {
        get {
            object obj = ResourceManager.GetObject("run32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap run64 {
        get {
            object obj = ResourceManager.GetObject("run64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap save32 {
        get {
            object obj = ResourceManager.GetObject("save32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap save32_green {
        get {
            object obj = ResourceManager.GetObject("save32-green", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap save64 {
        get {
            object obj = ResourceManager.GetObject("save64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap stop128 {
        get {
            object obj = ResourceManager.GetObject("stop128", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap support32 {
        get {
            object obj = ResourceManager.GetObject("support32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap tsslogo {
        get {
            object obj = ResourceManager.GetObject("tsslogo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap twitter32 {
        get {
            object obj = ResourceManager.GetObject("twitter32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap uncheck32 {
        get {
            object obj = ResourceManager.GetObject("uncheck32", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public static System.Drawing.Bitmap uncheck64 {
        get {
            object obj = ResourceManager.GetObject("uncheck64", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
